#!/usr/bin/env bash

leftwm command "UnloadTheme"

pkill compton
pkill dunst
if [ -e $HOME/.config/dunstrc.bak ]; then
    rm $HOME/.config/dunst/dunstrc
    mv $HOME/.config/dunst/dunstrc.bak $HOME/.config/dunst/dunstrc
fi
pkill fcitx5
pkill feh
pkill picom
pkill polybar

