#!/usr/bin/env bash

export $(dbus-launch)
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

command -v dunst && dunst &

command -v fcitx5 && fcitx5 &

if [ -x "$(command -v feh)" ]; then
    feh --bg-fill --randomize $SCRIPTPATH/wallpapers/*
    echo $SCRIPTPATH/wallpapers/*
fi

if [ -x "$(command -v picom)" ]; then
    picom &> /dev/null &
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v polybar)" ]; then
    pkill polybar
    monitors="$(polybar -m | sed s/:.*// | tac)"
    while read -r display; do
        MONITOR=$display polybar -c "$SCRIPTPATH/polybar.ini" mainbar &> /dev/null &
    done <<< "$monitors"
    exit 0
fi

